#!/usr/bin/env node
/**
 * Integration harness: runs Guard's CLI against every scenario under
 * `scenarios/` and writes a structured `RESULTS.md`. Used to verify the rule
 * catalog catches each crafted attack pattern from a real CLI invocation —
 * the closest we get to a virtual GitHub CI run without an actual network
 * registry.
 */
import { execFile } from 'node:child_process';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

const execAsync = promisify(execFile);
const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');
const GUARD_CLI = join(REPO_ROOT, 'dist', 'cli.js');
const SCENARIOS_DIR = join(__dirname, 'scenarios');
const RESULTS_PATH = join(__dirname, 'RESULTS.md');

const DEFAULT_ARGS = ['audit', '--offline', '--no-color'];

async function readJsonIfExists(path) {
  if (!existsSync(path)) return undefined;
  try {
    return JSON.parse(await readFile(path, 'utf8'));
  } catch {
    return undefined;
  }
}

async function runScenario(name) {
  const scenarioDir = join(SCENARIOS_DIR, name);
  const argsFile = await readJsonIfExists(join(scenarioDir, 'args.json'));
  const expectFile = await readJsonIfExists(join(scenarioDir, 'expect.json'));
  const description = (await readJsonIfExists(join(scenarioDir, 'description.json'))) ?? {};
  const args = argsFile?.args ?? DEFAULT_ARGS;

  let stdout = '';
  let stderr = '';
  let exitCode = 0;
  try {
    const result = await execAsync(process.execPath, [GUARD_CLI, ...args], {
      cwd: scenarioDir,
      env: { ...process.env, NO_COLOR: '1' },
    });
    stdout = result.stdout;
    stderr = result.stderr;
  } catch (error) {
    stdout = error.stdout ?? '';
    stderr = error.stderr ?? '';
    exitCode = typeof error.code === 'number' ? error.code : 1;
  }

  return { name, args, exitCode, stdout, stderr, expect: expectFile, description };
}

function summariseStdout(stdout) {
  // Pretty output has trailing blank lines; trim and indent.
  const trimmed = stdout.replace(/\s+$/, '');
  return trimmed.length > 0 ? trimmed : '(no stdout)';
}

function summariseStderr(stderr) {
  const trimmed = stderr.replace(/\s+$/, '');
  return trimmed.length > 0 ? trimmed : null;
}

function assess(result) {
  if (!result.expect) {
    return { pass: undefined, message: '(no `expect.json` — informational only)' };
  }
  const failures = [];
  if (typeof result.expect.exitCode === 'number' && result.exitCode !== result.expect.exitCode) {
    failures.push(`exit code expected ${result.expect.exitCode}, got ${result.exitCode}`);
  }
  if (typeof result.expect.containsRule === 'string') {
    const present = result.stdout.includes(result.expect.containsRule);
    if (!present) failures.push(`expected to find rule "${result.expect.containsRule}" in output`);
  }
  if (typeof result.expect.containsText === 'string') {
    const present = result.stdout.includes(result.expect.containsText);
    if (!present) failures.push(`expected to find text "${result.expect.containsText}" in output`);
  }
  return {
    pass: failures.length === 0,
    message: failures.length === 0 ? 'expectations met' : failures.join('; '),
  };
}

async function main() {
  if (!existsSync(GUARD_CLI)) {
    console.error(
      `Guard CLI not found at ${GUARD_CLI}. Run \`npm run build\` first.`,
    );
    process.exit(2);
  }

  const entries = await readdir(SCENARIOS_DIR, { withFileTypes: true });
  const scenarios = entries
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const results = [];
  for (const name of scenarios) {
    process.stdout.write(`Running ${name}... `);
    const result = await runScenario(name);
    const assessment = assess(result);
    result.assessment = assessment;
    results.push(result);
    process.stdout.write(
      assessment.pass === undefined
        ? 'done\n'
        : assessment.pass
          ? 'OK\n'
          : `FAIL (${assessment.message})\n`,
    );
  }

  const total = results.length;
  const passes = results.filter((r) => r.assessment.pass === true).length;
  const fails = results.filter((r) => r.assessment.pass === false).length;
  const noExpect = results.filter((r) => r.assessment.pass === undefined).length;

  const tick = '`';
  const lines = [
    '# Integration test results',
    '',
    `Generated by ${tick}npm run integration${tick} on ${new Date().toISOString().slice(0, 10)}.`,
    '',
    '## Summary',
    '',
    `- **${total} scenarios** run`,
    `- **${passes}** matched ${tick}expect.json${tick} exactly`,
    `- **${fails}** mismatched expectations`,
    `- **${noExpect}** informational only (no ${tick}expect.json${tick})`,
    '',
    'Each scenario is a self-contained directory shaped like a real Node.js',
    'project — `package.json`, `package-lock.json`, optionally `.npmrc` /',
    '`jadguard.config.json`. Guard runs against it with',
    `${tick}jadguard ${DEFAULT_ARGS.join(' ')}${tick} unless the scenario overrides via`,
    '`args.json`.',
    '',
    '## Scenarios',
    '',
  ];

  for (const r of results) {
    lines.push(`### ${r.name}`);
    lines.push('');
    if (r.description.summary) lines.push(`> ${r.description.summary}`);
    if (r.description.summary) lines.push('');
    if (r.description.attack) {
      lines.push(`**Attack vector:** ${r.description.attack}`);
      lines.push('');
    }
    lines.push(`**Command:** \`jadguard ${r.args.join(' ')}\``);
    lines.push('');
    lines.push(`**Exit code:** ${r.exitCode}`);
    lines.push('');
    if (r.expect) {
      lines.push(`**Assessment:** ${r.assessment.pass ? '✅' : '❌'} ${r.assessment.message}`);
      lines.push('');
    }
    lines.push('**Output:**');
    lines.push('');
    lines.push('```');
    lines.push(summariseStdout(r.stdout));
    const stderr = summariseStderr(r.stderr);
    if (stderr) {
      lines.push('--- stderr ---');
      lines.push(stderr);
    }
    lines.push('```');
    lines.push('');
  }

  await writeFile(RESULTS_PATH, lines.join('\n'), 'utf8');
  console.log(`\nWrote ${RESULTS_PATH}`);
  console.log(`${passes}/${total} scenarios met expectations` + (fails > 0 ? ` (${fails} failed)` : ''));
  process.exit(fails > 0 ? 1 : 0);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
